export const bioIntro = [
  "Trabajo como bailarín, acróbata, actor, maestro de danza y director/coreógrafo.Fui gimnasta federado desde 1987 hasta 1992 y Campeón Metropolitano de gimnasia deportiva en el año 1990 y sub-campeón en 1989. Desde el año 1999 comienzo a formarme en la Escuela de circo La Arena y en danza contemporánea y teatro con distintos maestros en Argentina y España.",

  "A partir del año 2000 y hasta la actualidad trabajo para distintas Compañías de teatro, circo y danza en Argentina y Europa , siempre combinando y generando diálogos entre mi trabajo como intérprete y creador con el de maestro. Comienzo a realizar mis creaciones propias a partir del año 2006. ",

  "Desde el año 2007 resido en Madrid, España.  Hasta ahora mis proyectos se han presentado en diferentes países como Alemania, Turquía, Argentina, Holanda, E.E.U.U., Grecia, Dinamarca, Chile, Brasil, España e Italia. ",

  "El objetivo de mis obras es lograr un trabajo escénico que, a través de la danza, la acrobacia y el teatro transmita emociones y conecte con el espectador, potenciando todos los sentidos en escena. Cada proyecto busca un lenguaje de movimiento propio y una poética escénica particular. ",

  "En Mayo de 2015  estrené “Solo Juntos”  en el Festival Umore Azoka de Leioa, en el País Vasco, España. Desde entonces “Solo Juntos” realizó más de 70  funciones en diferentes festivales de España, Brasil y resto de Europa. ",

  "El siguiente proyecto, “MyL”, creado junto con la bailarina de flamenco Mariana Collado, estrenó su versión corta en Mayo de 2019 también en el Festival Umore Azoka en Leioa, País Vasco y posteriormente se estrenó su versión larga MyL( 2.0) en Madrid. ",

  "En 2020 dirijo e interpreto junto con Rita Stepien y Peter James el video danza I AM THE OTHER . Este video es elegido en el Tanzahoi Festival de Hamburgo, Alemania y el Festival Choreoscope. Ambos se realizan en Septiembre de 2021. Ese mismo año dirijo junto a Candelaria Antelo a Maximiliano Sanford en el video danza Apparently alone que es producido y forma parte del Festival Dança em transito online de Brasil. ",

  "Mi creación “Mientras           tanto” se presenta como trabajo en proceso en el marco de la Muestra escénica Surge Madrid y recibe las Ayudas de la Creación a la Coreografía de parte de la Comunidad de Madrid. En 2022 mis proyectos “Mientras       tanto” y  MyL ( 2.0) se presentan en un Ciclo de dos meses (Abril y Mayo) en la Sala nave73 de madrid. MyL y MyL ( 2.0) han realizado  hasta la actualidad más de 65 funciones, recorriendo diferentes festivales, redes y circuitos nacionales e internacionales, en países como España, Grecia, Holanda, Francia y Alemania. En Junio de 2021 comienzo mi segunda creación junto a Mariana Collado, “Esto podría ser imposible”, gracias a la residencia de investigación otorgada al proyecto por el Centro Coreográfico Canal. Este proyecto ha sido elegido en la Muestra escénica Surge Madrid y se presenta como trabajo en proceso en octubre de 2021. Además recibe las residencias artísticas de la Compañía Nacional de Danza y la Beca Robisco para generar material audiovisual y fotográfico por el fotográfo Jesús Robisco. Actualmente estamos creando “Recuerdos de margaritas”, espectáculo de calle seleccionado para presentarse en el Festival Umore Azoka en Mayo de 2023.",

  "En octubre de 2022 estreno “Me las bailo todas” creación para 25 participantes que combina mis clases de Movimiento Lúcido con actuaciones en las calles de Madrid. Esta creación se realiza en el marco de la Muestra escénica Surge Madrid.",

  "Trabajo como director y maestro desarrollando y profundizando en mi metodología de creación “Movimiento Lúcido”, de la cual se desprenden sus variantes “Memoria Sensible”, “Contacto Lúcido” y “Acrobacia para tod@s”, que dialoga constantemente con mis creaciones,  de manera regular online y presencial para diferentes Compañías y Escuelas de circo y Conservatorios de danza de España, Alemania, Grecia, Suiza, Italia, Brasil, Bélgica y Argentina.  Estas clases se han realizado en el marco de la Escuela de artes vivas del Teatro Pradillo de Madrid, en el Akropoditi Festival en Syros en Grecia, en el programa NOD en Torino , Italia y en el Dance Days Chania Festival en Creta en Grecia,  entre otros.",
];
